learningpaths/urls.py
from django.urls import path
from .views import all_learning_paths, lp_detail

app_name = "learningpaths"

urlpatterns = [
    path('', all_learning_paths, name="all_learning_paths"),
    path('learningpath/<int:pk>/', lp_detail, name="lp_detail"),
]

realpythonlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learningpaths.urls'))
]

learningpaths/models.py
from django.db import models


# Create your models here.
class LearningPath(models.Model):
    title = models.CharField(max_length=50)
    url = models.CharField(max_length=100, null=True)
    image = models.CharField(max_length=100, null=True)


class Course(models.Model):
    title = models.CharField(max_length=50)
    complete = models.BooleanField()
    learning_path = models.ForeignKey(LearningPath, on_delete=models.CASCADE)

learningpaths/views.py
from django.shortcuts import render
from .models import LearningPath, Course


# Create your views here.
def all_learning_paths(request):
    lps = LearningPath.objects.values()
    for lp in lps:
        courses = Course.objects.values("complete").filter(learning_path=lp["id"])
        completed = [item['complete'] for item in courses].count(True)
        lp["progression"] = completed / len(courses) * 100
    return render(request,
                  "learningpaths/index.html",
                  {'learning_paths': lps, },
                  )

def lp_detail(request, pk):
    title = LearningPath.objects.get(pk=pk)
    courses = Course.objects.filter(learning_path=pk)
    return render(request,
                  "learningpaths/lp_detail.html",
                  {"title": title,
                  "courses": courses})

learningpaths/templates/learningpaths/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Real Python's Learning Paths</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
</head>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="https://cdn.realpython.com/static/real-python-logo.893c30edea53.svg" alt=""
                 height="30" class="d-inline-block align-text-top">
            Learning Paths - Tracking my progress
        </a>
    </div>
</nav>
<body class="container">
{% for learning_path in learning_paths %}
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            {% if learning_path.url %}
            <a href="{{ learning_path.url }}"><img class="img-fluid rounded-start"
                                                   src="{{ learning_path.image }}"
                                                   alt="Learning path's illustration">
            </a>
            {% else %}
            <img src="{{ learning_path.image }}" class="img-fluid rounded-start"
                 alt="Learning path's illustration">
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h4 class="card-title">{{ learning_path.title }}</h4>
                <p class="card-text"><small class="text-muted">Insert tags here</small></p>
                <p>Progression : {{ learning_path.progression }}%
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow={{ learning_path.progression }}
                         aria-valuemin="0" aria-valuemax="1"
                         style="width: {{ learning_path.progression }}%"></div>
                </div>
                </p>
                <p><a href="{% url 'learningpaths:lp_detail' learning_path.id %}"
                      class="btn btn-primary">Read
                    more</a></p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
</body>
</html>

learningpaths/templates/learningpaths/lp_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title.title}}</title>
    <meta name="viewport" content= "width=device-width, initial-scale=1.0">
</head>
<body>
    <h1>{{title.title}}</h1>
    {% for course in courses %}
        <h4>{{course.title}}</h4>
    {% endfor %}
</body>
</html>